version: '3.9'

services:
  frontend:
    container_name: clickbeard_frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  
  backend:
    container_name: clickbeard_backend
    build: ./backend
    ports:
      - 3003:3003
    working_dir: /backend
    command: /bin/sh -c "npm run seed && npm run start:dev"
    volumes: 
      - ./backend/src:/backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3003
      - JWT_SECRET=jwt_secret
      - DB_USER=postgres
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3003"]
      timeout: 10s
      retries: 5

  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    cap_add:
      - SYS_NICE
